name: GSC Insights Auto Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # Jalan tiap hari jam 00:00 UTC

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pandas google-api-python-client google-auth google-auth-oauthlib gspread

    - name: Run Python script
      env:
        GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      run: |
        python src/main.py

    - name: Setup Git for push
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and push CSV
      run: |
        git add gsc_data.csv gsc_insights.csv
        git commit -m "Auto update GSC insights [skip ci]" || echo "No changes to commit"
        git push origin main
