name: GSC Insights Auto Update

on:
  schedule:
    - cron: "0 0 * * *"  # Jalan setiap hari jam 00:00 UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install pandas google-api-python-client google-auth

    - name: Run script
      env:
        GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      run: python src/main.py

    - name: Commit and push updated CSV
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add gsc_insights.csv
        git commit -m "Update GSC insights"
        git push
